import os
from datetime import datetime


def generate_report(target):

    filename = target.replace(".", "_")

    report_file = f"reports/{filename}_report.txt"

    os.makedirs(
        "reports",
        exist_ok=True
    )

    with open(
        report_file,
        "w"
    ) as report:

        report.write(
            "=====================================\n"
        )

        report.write(
            "LIPAS VAPT REPORT\n"
        )

        report.write(
            "=====================================\n\n"
        )

        report.write(
            f"Target : {target}\n"
        )

        report.write(
            f"Date   : {datetime.now()}\n\n"
        )

        report.write(
            "This report was generated by LIPAS.\n"
        )

    print(
        f"\n[+] Report Saved: {report_file}"
    )
